import React, { useState } from 'react';
import { motion } from 'framer-motion';

const FAQ = () => {
  // State to track which question is currently open
  const [openIndex, setOpenIndex] = useState(null);

  // Toggle open/close question
  const toggleQuestion = (index) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  // FAQs data
  const faqs = [
    {
      question: "What is AI content detection?",
      answer:
        "AI content detection is the process of identifying text generated by artificial intelligence, ensuring the authenticity of written material.",
    },
    {
      question: "How accurate is your AI detection tool?",
      answer:
        "Our AI detection tool boasts a 98% accuracy rate, providing reliable results for your content needs.",
    },
    {
      question: "Can I try your services before committing?",
      answer:
        "We currently do not offer a free trial, but our pricing plans are flexible to suit your needs.",
    },
    {
      question: "What types of content can I analyze?",
      answer:
        "You can analyze any text, including articles, essays, marketing content, and more.",
    },
    {
      question: "How does the automatic AI humanization feature work?",
      answer:
        "This upcoming feature will convert AI-generated text into more relatable and engaging content, tailored for your audience.",
    },
    {
      question: "What are AI-powered learning paths?",
      answer:
        "Our learning paths provide tailored courses and resources to help you gain essential skills for navigating the AI landscape.",
    },
    {
      question: "How do I access the reports after content analysis?",
      answer:
        "You can download your detailed report immediately after your content has been checked.",
    },
    {
      question: "Is my content safe with Ganaxy.ai?",
      answer:
        "Absolutely! We prioritize your privacy and ensure that all submitted content is secure and confidential.",
    },
    {
      question: "Can I cancel my subscription anytime?",
      answer:
        "Yes, you can cancel your subscription at any time without any penalties.",
    },
    {
      question: "What payment methods do you accept?",
      answer:
        "We accept major credit cards and secure online payment options for your convenience.",
    },
    {
      question: "Do you offer support for using your services?",
      answer:
        "Yes, our dedicated support team is available 24/7 to assist you with any questions or issues.",
    },
    {
      question: "How can I provide feedback on your services?",
      answer:
        "We welcome your feedback! You can reach out to us through our contact page or email us directly.",
    },
  ];

  return (
    <section className="relative w-full bg-purple-50 py-16 px-4 md:px-8 lg:py-24 lg:px-16">
      <div className="max-w-4xl mx-auto text-center">
        <h2 className="text-3xl md:text-4xl font-bold text-pink-700 mb-8">
          Frequently Asked Questions
        </h2>
        <div className="bg-white shadow-lg rounded-lg">
          {faqs.map((faq, index) => (
            <div key={index} className="border-b border-purple-200">
              <motion.div
                className="cursor-pointer p-4 flex justify-between items-center"
                onClick={() => toggleQuestion(index)}
                initial={{ backgroundColor: '#ffffff' }}
                whileHover={{ backgroundColor: '#fce4ec' }}
              >
                <h3 className="text-left text-lg font-semibold text-purple-800">
                  {faq.question}
                </h3>
                <motion.span
                  className="text-pink-700"
                  animate={{ rotate: openIndex === index ? 45 : 0 }}
                  transition={{ duration: 0.3 }}
                >
                  +
                </motion.span>
              </motion.div>
              {openIndex === index && (
                <motion.div
                  className="bg-purple-100 p-4 text-left text-purple-800"
                  initial={{ height: 0, opacity: 0 }}
                  animate={{ height: 'auto', opacity: 1 }}
                  transition={{ duration: 0.3 }}
                >
                  {faq.answer}
                </motion.div>
              )}
            </div>
          ))}
        </div>
        <div className="flex flex-col md:flex-row justify-center items-center mt-12 space-y-4 md:space-y-0 md:space-x-8">
          <button className="bg-pink-600 hover:bg-pink-700 text-white py-2 px-6 rounded shadow-lg transition-all duration-300">
            Contact Us
          </button>
          <button className="bg-purple-600 hover:bg-purple-700 text-white py-2 px-6 rounded shadow-lg transition-all duration-300">
            Get Started Now
          </button>
        </div>
      </div>
    </section>
  );
};

export default FAQ;
